Some more fixes to travis build failure on OSX.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,18 +32,25 @@ before_script:
     - echo "OSX related"
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
           brew update;
-          brew install cmake;
-          brew install homebrew/science/gsl homebrew/science/hdf5;
-          brew install homebrew/science/libsbml;
-          brew install homebrew/python/numpy;
-          brew install python3;
-          brew install boost;
+          brew outdated cmake || brew install cmake;
+          brew outdated gsl || brew install gsl;
+          brew outdated hdf5 || brew install homebrew/science/hdf5;
+          brew outdated libsbml || brew install homebrew/science/libsbml;
+          brew outdated python || brew install python;
+          brew outdated numpy || brew install homebrew/python/numpy;
+          brew link --overwrite numpy || echo "Failed to link numpy";
+          # Numpy caveats
+          mkdir -p $HOME/Library/Python/2.7/lib/python/site-packages;
+          echo 'import sys; sys.path.insert(1, "/usr/local/lib/python2.7/site-packages")' \
+            >> $HOME/Library/Python/2.7/lib/python/site-packages/homebrew.pth;
+         # Python 3. 
+          brew outdated python3 || brew install python3;
       else
           sudo apt-get install -qq libxml2-dev libbz2-dev;
           sudo apt-get install -qq libhdf5-serial-dev;
           sudo apt-get install -qq make cmake;
-          sudo apt-get install -qq  python-numpy python-matplotlib python-networkx;
-          sudo apt-get install -qq  python3-numpy python3-matplotlib python3-dev;
+          sudo apt-get install -qq python-numpy python-matplotlib python-networkx;
+          sudo apt-get install -qq python3-numpy python3-matplotlib python3-dev;
           sudo apt-get install -qq libboost-all-dev;
           sudo apt-get install -qq libgsl0-dev;
           sudo apt-get install -qq python-pip python3-pip;
