Using setup.py file to build and install pymoose.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,18 +4,20 @@ on: [push]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-    
     steps:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: |
         sudo apt update
-        sudo apt install libgsl-dev g++ cmake python3-dev python3-numpy
+        sudo apt install libgsl-dev g++ cmake python3-pip python3-numpy python3-matplotlib
+        sudo apt install python-dev python-numpy python-matplotlib python-pip
     - name: configure
-      run: mkdir -p build && cd build && cmake ..
     - name: make
-      run: cd build && make
-    - name: Test
-      run: cd build && ctest --output-on-failure 
+      run: |
+        python setup.py install test
+        python3 setup.py install test
+    - name: Post Install
+      run: |
+        python3 -c "import moose;moose.test()" || echo "Failed python3 tests"
+        python2 -c "import moose;moose.test()" || echo "Failed python2 tests"
